# Exceptions




<div class="phpcode"><span class="html">
When catching an exception inside a namespace it is important that you escape to the global space:<br><br><span class="default">&lt;?php<br> </span><span class="keyword">namespace </span><span class="default">SomeNamespace</span><span class="keyword">;<br><br> class </span><span class="default">SomeClass </span><span class="keyword">{<br><br>&#xA0; function </span><span class="default">SomeFunction</span><span class="keyword">() {<br>&#xA0;&#xA0; try {<br>&#xA0; &#xA0; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&apos;Some Error Message&apos;</span><span class="keyword">);<br>&#xA0;&#xA0; } catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; </span><span class="default">var_dump</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br>&#xA0;&#xA0; }<br>&#xA0; }<br><br> }<br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
If a TRY has a FINALLY, a RETURN either in the TRY or a CATCH won&apos;t terminate the script. Code in the same block after the RETURN will not be executed, and the RETURN itself will be &quot;copied&quot; to the bottom of the FINALLY block to be executed.<br><br>a RETURN in the FINALLY block will override value(s) returned from the TRY or a CATCH block.<br><br>An EXIT or a DIE always terminate the script after themselves.<br><br>code 1<br><br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">foo</span><span class="keyword">(){<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar </span><span class="keyword">= </span><span class="default">1</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&apos;I am Wu Xiancheng.&apos;</span><span class="keyword">);<br>&#xA0; &#xA0; &#xA0; &#xA0; }catch(</span><span class="default">Exception $e</span><span class="keyword">){<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">$bar</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar</span><span class="keyword">--; </span><span class="comment">// this line will be ignored<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">}finally{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar</span><span class="keyword">++;<br>&#xA0; &#xA0; &#xA0; &#xA0; }<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; echo </span><span class="default">foo</span><span class="keyword">(); </span><span class="comment">// 2<br></span><span class="default">?&gt;<br></span><br>code 2<br><br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">foo</span><span class="keyword">(){<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar </span><span class="keyword">= </span><span class="default">1</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&apos;I am Wu Xiancheng.&apos;</span><span class="keyword">);<br>&#xA0; &#xA0; &#xA0; &#xA0; }catch(</span><span class="default">Exception $e</span><span class="keyword">){<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">$bar</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar</span><span class="keyword">--; </span><span class="comment">// this line will be ignored<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">}finally{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar</span><span class="keyword">++;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">$bar</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; }<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; echo </span><span class="default">foo</span><span class="keyword">(); </span><span class="comment">//2 <br></span><span class="default">?&gt;<br></span><br>code 3<br><br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">foo</span><span class="keyword">(){<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar </span><span class="keyword">= </span><span class="default">1</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&apos;I am Wu Xiancheng.&apos;</span><span class="keyword">);<br>&#xA0; &#xA0; &#xA0; &#xA0; }catch(</span><span class="default">Exception $e</span><span class="keyword">){<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">$bar</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">$bar</span><span class="keyword">--; </span><span class="comment">// this line will be ignored<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">}finally{<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">100</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; }<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; echo </span><span class="default">foo</span><span class="keyword">(); </span><span class="comment">//100<br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
If you intend on creating a lot of custom exceptions, you may find this code useful.&#xA0; I&apos;ve created an interface and an abstract exception class that ensures that all parts of the built-in Exception class are preserved in child classes.&#xA0; It also properly pushes all information back to the parent constructor ensuring that nothing is lost.&#xA0; This allows you to quickly create new exceptions on the fly.&#xA0; It also overrides the default __toString method with a more thorough one.<br><br><span class="default">&lt;?php<br></span><span class="keyword">interface </span><span class="default">IException<br></span><span class="keyword">{<br>&#xA0; &#xA0; </span><span class="comment">/* Protected methods inherited from Exception class */<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getMessage</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// Exception message <br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getCode</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// User-defined Exception code<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getFile</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// Source filename<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getLine</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// Source line<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getTrace</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// An array of the backtrace()<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">getTraceAsString</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// Formated string of trace<br>&#xA0; &#xA0; <br>&#xA0; &#xA0; /* Overrideable methods inherited from Exception class */<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">__toString</span><span class="keyword">();&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// formated string for display<br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">);<br>}<br><br>abstract class </span><span class="default">CustomException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">implements </span><span class="default">IException<br></span><span class="keyword">{<br>&#xA0; &#xA0; protected </span><span class="default">$message </span><span class="keyword">= </span><span class="string">&apos;Unknown exception&apos;</span><span class="keyword">;&#xA0; &#xA0;&#xA0; </span><span class="comment">// Exception message<br>&#xA0; &#xA0; </span><span class="keyword">private&#xA0;&#xA0; </span><span class="default">$string</span><span class="keyword">;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// Unknown<br>&#xA0; &#xA0; </span><span class="keyword">protected </span><span class="default">$code&#xA0; &#xA0; </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// User-defined exception code<br>&#xA0; &#xA0; </span><span class="keyword">protected </span><span class="default">$file</span><span class="keyword">;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// Source filename of exception<br>&#xA0; &#xA0; </span><span class="keyword">protected </span><span class="default">$line</span><span class="keyword">;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">// Source line of exception<br>&#xA0; &#xA0; </span><span class="keyword">private&#xA0;&#xA0; </span><span class="default">$trace</span><span class="keyword">;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0;&#xA0; </span><span class="comment">// Unknown<br><br>&#xA0; &#xA0; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">)<br>&#xA0; &#xA0; {<br>&#xA0; &#xA0; &#xA0; &#xA0; if (!</span><span class="default">$message</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">$this</span><span class="keyword">(</span><span class="string">&apos;Unknown &apos;</span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">));<br>&#xA0; &#xA0; &#xA0; &#xA0; }<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; <br>&#xA0; &#xA0; public function </span><span class="default">__toString</span><span class="keyword">()<br>&#xA0; &#xA0; {<br>&#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">) . </span><span class="string">&quot; &apos;</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">message</span><span class="keyword">}</span><span class="string">&apos; in </span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">file</span><span class="keyword">}</span><span class="string">(</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">line</span><span class="keyword">}</span><span class="string">)\n&quot;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">. </span><span class="string">&quot;</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">()}</span><span class="string">&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; }<br>}<br></span><span class="default">?&gt;<br></span><br>Now you can create new exceptions in one line:<br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">TestException </span><span class="keyword">extends </span><span class="default">CustomException </span><span class="keyword">{}<br></span><span class="default">?&gt;<br></span><br>Here&apos;s a test that shows that all information is properly preserved throughout the backtrace.<br><br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">exceptionTest</span><span class="keyword">()<br>{<br>&#xA0; &#xA0; try {<br>&#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">TestException</span><span class="keyword">();<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; catch (</span><span class="default">TestException $e</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="string">&quot;Caught TestException (&apos;</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">&apos;)\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="string">&quot;Caught Exception (&apos;</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">&apos;)\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; }<br>}<br><br>echo </span><span class="string">&apos;&lt;pre&gt;&apos; </span><span class="keyword">. </span><span class="default">exceptionTest</span><span class="keyword">() . </span><span class="string">&apos;&lt;/pre&gt;&apos;</span><span class="keyword">;<br></span><span class="default">?&gt;<br></span><br>Here&apos;s a sample output:<br><br>Caught TestException (&apos;Unknown TestException&apos;)<br>TestException &apos;Unknown TestException&apos; in C:\xampp\htdocs\CustomException\CustomException.php(31)<br>#0 C:\xampp\htdocs\CustomException\ExceptionTest.php(19): CustomException-&gt;__construct()<br>#1 C:\xampp\htdocs\CustomException\ExceptionTest.php(43): exceptionTest()<br>#2 {main}</span>
</div>
  

#


<div class="phpcode"><span class="html">
catch doesn&apos;t check for the existence of the Exception class, so avoid typo.<br><br><span class="default">&lt;?php<br>&#xA0;&#xA0; </span><span class="keyword">class </span><span class="default">MyException </span><span class="keyword">extends </span><span class="default">Exception<br>&#xA0;&#xA0; </span><span class="keyword">{<br>&#xA0; &#xA0; &#xA0; ...<br>&#xA0;&#xA0; }<br><br>&#xA0;&#xA0; try<br>&#xA0;&#xA0; {<br>&#xA0; &#xA0; &#xA0; throw new </span><span class="default">MyException</span><span class="keyword">(...);<br>&#xA0;&#xA0; }<br>&#xA0;&#xA0; catch (</span><span class="default">MuException $e</span><span class="keyword">) </span><span class="comment">// &lt;--- typo<br>&#xA0;&#xA0; </span><span class="keyword">{<br>&#xA0; &#xA0; &#xA0; ...<br>&#xA0;&#xA0; }<br></span><span class="default">?&gt;</span> <br><br>You WON&apos;T get<br>&#xA0;&#xA0; Fatal error: Class MuException could not be loaded ...<br><br>You WILL get<br>&#xA0;&#xA0; Fatal error: Uncaught exception &apos;MyException&apos; ...</span>
</div>
  

#


<div class="phpcode"><span class="html">
Custom error handling on entire pages can avoid half rendered pages for the users:<br><br><span class="default">&lt;?php<br>ob_start</span><span class="keyword">();<br>try {<br>&#xA0; &#xA0; </span><span class="comment">/*contains all page logic <br>&#xA0; &#xA0; and throws error if needed*/<br>&#xA0; &#xA0; </span><span class="keyword">...<br>} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; </span><span class="default">ob_end_clean</span><span class="keyword">();<br>&#xA0; </span><span class="default">displayErrorPage</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br>}<br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
Using a return statement inside a finally block will override any other return statement or thrown exception from the try block and all defined catch blocks.&#xA0;&#xA0; Code execution in the parent stack will continue as if the exception was never thrown.&#xA0; <br><br>Frankly this is a good design decision because it means I can optionally dismiss all thrown exceptions from 1 or more catch blocks in one place, without having to nest my whole try block inside an additional (and otherwise needless) try/catch block.<br><br>This is the same behavior as Java, whereas C# throws a compile time error when a return statement exists inside a finally block.&#xA0; So I figured it was worth pointing out to PHP devs who may not have any exposure to finally blocks or how other languages do it.<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">function </span><span class="default">asdf</span><span class="keyword">()<br>{<br>&#xA0; &#xA0; try {<br>&#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&apos;error&apos;</span><span class="keyword">);<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="string">&quot;An error occurred&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; throw </span><span class="default">$e</span><span class="keyword">;<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; finally {<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; </span><span class="comment">//This overrides the exception as if it were never thrown<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">return </span><span class="string">&quot;\nException erased&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; }<br>}<br><br>try {<br>&#xA0; &#xA0; echo </span><span class="default">asdf</span><span class="keyword">();<br>}<br>catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; echo </span><span class="string">&quot;\nResult: &quot; </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>}<br></span><span class="default">?&gt;<br></span><br>The output from above will look like this:<br><br>&#xA0; &#xA0; An error occurred<br>&#xA0; &#xA0; Exception erased<br><br>Without the return statement in the finally block it would look like this:<br><br>&#xA0; &#xA0; An error occurred<br>&#xA0; &#xA0; Result: error</span>
</div>
  

#


<div class="phpcode"><span class="html">
Type declarations will trigger Uncaught TypeError when a different type is passed. And it cannot be caught with the Exception class.<br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">xc</span><span class="keyword">(array </span><span class="default">$a</span><span class="keyword">){&#xA0; &#xA0; &#xA0; &#xA0; <br>&#xA0; &#xA0; }&#xA0; &#xA0; <br>&#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">xc</span><span class="keyword">(</span><span class="default">4</span><span class="keyword">);<br>&#xA0; &#xA0; }catch (</span><span class="default">Exception $e</span><span class="keyword">){ </span><span class="comment">// failed to catch it<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="keyword">echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>&#xA0; &#xA0; }<br></span><span class="default">?&gt;<br></span><br>You should use TypeError instead for PHP 7+,<br><br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">xc</span><span class="keyword">(array </span><span class="default">$a</span><span class="keyword">){&#xA0; &#xA0; <br>&#xA0; &#xA0; }&#xA0; &#xA0; <br>&#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">xc</span><span class="keyword">(</span><span class="default">4</span><span class="keyword">);<br>&#xA0; &#xA0; }catch (</span><span class="default">TypeError $e</span><span class="keyword">){<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>&#xA0; &#xA0; }<br></span><span class="default">?&gt;<br></span><br>In php version prior to 7.0, you should translate Catchable fatal errors to an exception and then catch it.<br><br><span class="default">&lt;?php<br>&#xA0; &#xA0; </span><span class="keyword">function </span><span class="default">exceptionErrorHandler</span><span class="keyword">(</span><span class="default">$errNumber</span><span class="keyword">, </span><span class="default">$errStr</span><span class="keyword">, </span><span class="default">$errFile</span><span class="keyword">, </span><span class="default">$errLine </span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$errStr</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$errNumber</span><span class="keyword">, </span><span class="default">$errFile</span><span class="keyword">, </span><span class="default">$errLine</span><span class="keyword">);<br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; </span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">&apos;exceptionErrorHandler&apos;</span><span class="keyword">);<br>&#xA0; &#xA0; function </span><span class="default">s</span><span class="keyword">(array </span><span class="default">$a</span><span class="keyword">){&#xA0; &#xA0; &#xA0; &#xA0; <br>&#xA0; &#xA0; }<br>&#xA0; &#xA0; try{<br>&#xA0; &#xA0; &#xA0; &#xA0; </span><span class="default">s</span><span class="keyword">(</span><span class="default">4</span><span class="keyword">);<br>&#xA0; &#xA0; }catch (</span><span class="default">Exception $e</span><span class="keyword">){<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>&#xA0; &#xA0; }<br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
Sometimes you want a single catch() to catch multiple types of Exception. In a language like Python, you can specify multiple types in a catch(), but in PHP you can only specify one. This can be annoying when you want handle many different Exceptions with the same catch() block.<br><br>However, you can replicate the functionality somewhat, because catch(&lt;classname&gt; $var) will match the given &lt;classname&gt; *or any of it&apos;s sub-classes*.<br><br>For example:<br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">DisplayException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br>class </span><span class="default">FileException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br>class </span><span class="default">AccessControl </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br></span><span class="keyword">class </span><span class="default">IOError </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br><br></span><span class="keyword">try {<br>&#xA0; if(!</span><span class="default">is_readable</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br>&#xA0; &#xA0;&#xA0; throw new </span><span class="default">IOError</span><span class="keyword">(</span><span class="string">&quot;File is not readable!&quot;</span><span class="keyword">);<br>&#xA0; if(!</span><span class="default">user_has_access_to_file</span><span class="keyword">(</span><span class="default">$someuser</span><span class="keyword">, </span><span class="default">$somefile</span><span class="keyword">))<br>&#xA0; &#xA0;&#xA0; throw new </span><span class="default">AccessControl</span><span class="keyword">(</span><span class="string">&quot;Permission denied!&quot;</span><span class="keyword">);<br>&#xA0; if(!</span><span class="default">display_file</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br>&#xA0; &#xA0;&#xA0; throw new </span><span class="default">DisplayException</span><span class="keyword">(</span><span class="string">&quot;Couldn&apos;t display file!&quot;</span><span class="keyword">);<br><br>} catch (</span><span class="default">FileException $e</span><span class="keyword">) {<br>&#xA0; </span><span class="comment">// This block will catch FileException, AccessControl or IOError exceptions, but not Exceptions or DisplayExceptions.<br>&#xA0; </span><span class="keyword">echo </span><span class="string">&quot;File error: &quot;</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>&#xA0; exit(</span><span class="default">1</span><span class="keyword">);<br>}<br></span><span class="default">?&gt;<br></span><br>Corollary: If you want to catch *any* exception, no matter what the type, just use &quot;catch(Exception $var)&quot;, because all exceptions are sub-classes of the built-in Exception.</span>
</div>
  

#


<div class="phpcode"><span class="html">
If you are using a namespace, you must indicate the global namespace when using Exceptions.<br><span class="default">&lt;?php<br></span><span class="keyword">namespace </span><span class="default">alpha</span><span class="keyword">;<br>function </span><span class="default">foo</span><span class="keyword">(){<br>&#xA0; &#xA0; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&quot;Something is wrong!&quot;</span><span class="keyword">);<br>&#xA0; &#xA0; </span><span class="comment">// throw new Exception(&quot;&quot;); will fail<br></span><span class="keyword">}<br><br>try {<br>&#xA0; &#xA0; </span><span class="default">foo</span><span class="keyword">();<br>} catch( \</span><span class="default">Exception $e </span><span class="keyword">) {<br>&#xA0; &#xA0; </span><span class="comment">// catch( Exception $e ) will give no warning, but will not catch Exception<br>&#xA0; &#xA0; </span><span class="keyword">echo </span><span class="string">&quot;ERROR: </span><span class="default">$e</span><span class="string">&quot;</span><span class="keyword">;<br>}<br><br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
&#x2018;Normal execution (when no exception is thrown within the try block, *or when a catch matching the thrown exception&#x2019;s class is not present*) will continue after that last catch block defined in sequence.&#x2019;<br><br>&#x2018;If an exception is not caught, a PHP Fatal Error will be issued with an &#x201C;Uncaught Exception &#x2026;&#x201D; message, unless a handler has been defined with set_exception_handler().&#x2019;<br><br>These two sentences seem a bit contradicting about what happens &#x2018;when a catch matching the thrown exception&#x2019;s class is not present&#x2019; (and the second sentence is actually correct).</span>
</div>
  

#


<div class="phpcode"><span class="html">
Just an example why finally blocks are usefull (5.5)<br><br><span class="default">&lt;?php<br><br></span><span class="comment">//without catch<br></span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br>&#xA0; try {<br>&#xA0; &#xA0; </span><span class="comment">//do something that throws an exeption<br>&#xA0; </span><span class="keyword">}<br>&#xA0; finally {<br>&#xA0; &#xA0; </span><span class="comment">//this code will be executed even when the exception is executed<br>&#xA0; </span><span class="keyword">}<br>}<br><br>function </span><span class="default">example2</span><span class="keyword">() {<br>&#xA0; try {<br>&#xA0; &#xA0;&#xA0; </span><span class="comment">//open sql connection check user as example<br>&#xA0; &#xA0;&#xA0; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br>&#xA0; &#xA0; &#xA0; &#xA0; return </span><span class="default">false</span><span class="keyword">;<br>&#xA0; &#xA0;&#xA0; }<br>&#xA0; }<br>&#xA0; finally {<br>&#xA0; &#xA0; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br>&#xA0; </span><span class="keyword">}<br>}<br><br></span><span class="default">?&gt;</span>
</span>
</div>
  

#


<div class="phpcode"><span class="html">
The &quot;finally&quot; block can change the exception that has been throw by the catch block.<br><br><span class="default">&lt;?php<br></span><span class="keyword">try{<br>&#xA0; &#xA0; &#xA0; &#xA0; try {<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&quot;Hello&quot;</span><span class="keyword">);<br>&#xA0; &#xA0; &#xA0; &#xA0; } catch(\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">&quot; catch in\n&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw </span><span class="default">$e</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; } finally {<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">&quot; finally \n&quot;</span><span class="keyword">;<br>&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">&quot;Bye&quot;</span><span class="keyword">);<br>&#xA0; &#xA0; &#xA0; &#xA0; }<br>} catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&#xA0; &#xA0; &#xA0; &#xA0; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">&quot; catch out\n&quot;</span><span class="keyword">;<br>}<br></span><span class="default">?&gt;<br></span><br>The output is:<br><br>Hello catch in<br>Hello finally <br>Bye catch out</span>
</div>
  

#

[Official documentation page](https://www.php.net/manual/en/language.exceptions.php)

**[To root](/)**